#include <QtTest>
#include <QDir>
#include <preprocessing/preprocessor.h>
#include <inference/inferenceengine.h>
#include <postprocessing/postprocessor.h>
#include <utils/niftiVolume.h>
#include <utils/env_path.h>
#include "test_utils.h"

using namespace preprocessing;
using namespace postprocessing;

/*
@brief End-to-end test of backend pipeline: from raw T1 input to final post-processed output in
patient space. Permits to validate the integration of all components (preprocessing, inference,
postprocessing) before integrating in the GUI. The test checks that the final output is generated 
and has the expected dimensions.
*/

class TestFullPipeline : public QObject {
    Q_OBJECT

private slots:
    void testEndToEndInference() {
        QString inputT1 = QDir(Paths::baseDir()).filePath("test/test_data/sub-r001s002-T1w.nii.gz");
        QString outputDir = QCoreApplication::applicationDirPath() + "/full_pipeline_test";
        QDir().mkpath(outputDir);

        AnimaWrapper *wrapper = new AnimaWrapper(this);
        
        // ---------------------------------------------------------
        // STEP 1 : PREPROCESSING
        // ---------------------------------------------------------
        qDebug() << "--- [STEP 1] Preprocessing ---";
        Resampling resampler;
        QString atlasPath = Paths::atlasDir() + "/Reference_T1.nrrd";
        BrainExtraction brainExtractor(wrapper, atlasPath);
        Preprocessor preproc(&resampler, &brainExtractor, wrapper);

        PreprocessedVolume preprocResult;
        try {
            preprocResult = preproc.preprocess(inputT1, "", outputDir, false);
        } catch (const std::exception &e) {
            QFAIL(qPrintable(QString("Preprocessing failed: %1").arg(e.what())));
        }

        QString preprocFile = outputDir + "/preprocessed_for_inference.nii.gz";
        NiftiVolume volPreproc;
        volPreproc.data = preprocResult.data;
        volPreproc.spacing = preprocResult.spacing;
        NiftiVolume::saveNifti(preprocFile, volPreproc);

        // ---------------------------------------------------------
        // STEP 2 : INFERENCE
        // ---------------------------------------------------------
        qDebug() << "--- [STEP 2] Inference ---";
        InferenceEngine engine;
        QString modelPath = Paths::modelDir() + "/Monomodal.onnx";
        QString inferenceOut = outputDir + "/inference_raw_output.nii.gz";

        NiftiVolume inferenceResult;
        try {
            inferenceResult = engine.run(modelPath, preprocFile, inferenceOut, "input", "output");
        } catch (const std::exception &e) {
            QFAIL(qPrintable(QString("Inference failed: %1").arg(e.what())));
        }
        QVERIFY(inferenceResult.data.size() > 0);

        // ---------------------------------------------------------
        // STEP 3 : POSTPROCESSING
        // ---------------------------------------------------------
        qDebug() << "--- [STEP 3] Postprocessing ---";
        Postprocessor postproc(wrapper);
        
        // get BBox and Trsf_path generated by preproc at step 1
        std::array<std::array<int, 2>, 3> bbox = preprocResult.bbox; 

        qDebug() << "Bounding box récupérée du pré-traitement:" 
                 << "X:" << bbox[0][0] << "-" << bbox[0][1] 
                 << "Y:" << bbox[1][0] << "-" << bbox[1][1] 
                 << "Z:" << bbox[2][0] << "-" << bbox[2][1];

        qDebug() << "Padding appliqué lors du pré-traitement:" 
                 << "X:" << preprocResult.padding[0][0] << "-" << preprocResult.padding[0][1] 
                 << "Y:" << preprocResult.padding[1][0] << "-" << preprocResult.padding[1][1] 
                 << "Z:" << preprocResult.padding[2][0] << "-" << preprocResult.padding[2][1];

        qDebug() << "Original image shape récupérée du pré-traitement:" 
                 << preprocResult.original_shape.x() << "x" 
                 << preprocResult.original_shape.y() << "x" 
                 << preprocResult.original_shape.z();

        qDebug() << "Trsf path récupéré du pré-traitement:" << preprocResult.trsf_path;
        

        try {
            postproc.postprocess(
                inferenceResult.data, 
                preprocResult, 
                bbox, 
                0.5f,   // threshold
                true,   // save_pmap
                outputDir, 
                preprocResult.trsf_path
            );
        } catch (const std::exception &e) {
            QFAIL(qPrintable(QString("Postprocessing failed: %1").arg(e.what())));
        }

        // ---------------------------------------------------------
        // STEP 4 : FINAL CHECKS
        // ---------------------------------------------------------
        QString finalFile = outputDir + "/final_result_to_patient.nii.gz";
        QVERIFY2(QFile::exists(finalFile), "Le fichier final en espace patient n'a pas été généré.");

        NiftiVolume finalVol = NiftiVolume::loadNifti(finalFile);

        qDebug() << "Dimensions du volume final post-traité:" 
                 << finalVol.data.dimension(0) << "x" 
                 << finalVol.data.dimension(1) << "x" 
                 << finalVol.data.dimension(2) << "x" 
                 << finalVol.data.dimension(3);
        
        // Vérification des dimensions : Doit être identique au T1 original (ex: 256x256x176)
        NiftiVolume originalT1 = NiftiVolume::loadNifti(inputT1);

        qDebug() << "Dimensions du T1 original:" 
                 << originalT1.data.dimension(0) << "x" 
                 << originalT1.data.dimension(1) << "x" 
                 << originalT1.data.dimension(2) << "x" 
                 << originalT1.data.dimension(3);

        QCOMPARE(finalVol.data.dimension(1), originalT1.data.dimension(1));
        QCOMPARE(finalVol.data.dimension(2), originalT1.data.dimension(2));
        QCOMPARE(finalVol.data.dimension(3), originalT1.data.dimension(3));

        qDebug() << "--- [SUCCESS] Pipeline complet terminé avec succès ---";
    }
};

QTEST_MAIN(TestFullPipeline)
#include "test_full_pipeline.moc"