# SPDX-License-Identifier: AGPL-3.0-or-later

set(CPACK_GENERATOR "DragNDrop")

set(CPACK_DMG_VOLUME_NAME "${CPACK_PACKAGE_NAME} v${CPACK_PACKAGE_VERSION}")
set(CPACK_DMG_FORMAT "UDZO")
set(CPACK_DMG_FILESYSTEM "APFS")

# DMG Icon
if(EXISTS "${PROJECT_SOURCE_DIR}/resources/DmgVolumeIcon.icns")
    set(CPACK_DMG_VOLUME_ICON "${PROJECT_SOURCE_DIR}/resources/DmgVolumeIcon.icns")
endif()

# MacOS nundle configuration 
set(CPACK_BUNDLE_NAME "${CPACK_PACKAGE_NAME}")
set(CPACK_BUNDLE_ICON "${PROJECT_SOURCE_DIR}/resources/StrokeSegPWR.icns")
set(CPACK_BUNDLE_PLIST "${CMAKE_SOURCE_DIR}/cmake/package/Info.plist.in")

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}_${CPACK_PACKAGE_VERSION}_macOS_${CMAKE_SYSTEM_PROCESSOR}")

set(CPACK_COMPONENTS_ALL_IN_ONE_PACKAGE 1)
set(CPACK_MONOLITHIC_INSTALL 1)
